const { withNativeFederation, shareAll, share } = require('@angular-architects/native-federation/config');

module.exports = withNativeFederation({
  name: 'remote-angular20',

  exposes: {
    './app.routes': './src/app/app.routes.ts',
  },

  shared: {
    ...shareAll({ singleton: true, strictVersion: true, requiredVersion: 'auto' }),
    // 'ngx-permissions': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
    ...share({
      // '@angular/core': { singleton: true, strictVersion: false, requiredVersion: '>=20.0.0 <21.0.0' },
      // '@angular/common': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // '@angular/router': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // '@ngrx/signals': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'ngx-permissions': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // '@jsverse/transloco': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // '@angular/forms': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // primeng: { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      //
      // 'primeng/config': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/api': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/base': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/usestyle': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/usestyle': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/button': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/datepicker': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/autofocus': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/badge': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/basecomponent': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/fluid': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/dom': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/ripple': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/baseinput': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // //
      // 'primeng/icons': { singleton: true, strictVersion: true, requiredVersion: 'auto', includeSecondaries: true },
      // 'primeng/icons/baseicon': {
      //   singleton: true,
      //   strictVersion: true,
      //   requiredVersion: 'auto',
      //   includeSecondaries: true,
      // },
      // 'primeng/icons/angledoubleleft': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/icons/angledoubleright': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/icons/angledoubleup': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/icons/angledoubledown': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/icons/angledown': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // --
      // '@angular/platform-browser': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // '@angular/animations': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // --
      // 'primeng/button': { singleton: true, strictVersion: true, requiredVersion: 'auto' },
      // 'primeng/datepicker': { singleton: true, strictVersion: true, requiredVersion: 'auto', includeSecondaries: true },
      // --
      // '@primeuix/themes': {
      //   singleton: true,
      //   strictVersion: true,
      //   requiredVersion: 'auto',
      //   includeSecondaries: true, // Necesario todos los sub packages
      //   build: 'separate',
      // },
    }),
  },

  skip: [
    'rxjs/ajax',
    'rxjs/fetch',
    'rxjs/testing',
    'rxjs/webSocket',
    'consola', // puede generar error si esta activo , ignoreUnusedDeps
    /* _____ PrimeNg _____ */
    // 'primeng/accordion',
    // 'primeng/animateonscroll',
    // // 'primeng/api',
    // 'primeng/autocomplete',
    // // 'primeng/autofocus',
    // 'primeng/avatar',
    // 'primeng/avatargroup',
    // // 'primeng/badge',
    // // 'primeng/base',
    // // 'primeng/basecomponent',
    // // 'primeng/baseeditableholder',
    // // 'primeng/baseinput',
    // 'primeng/blockui',
    // 'primeng/breadcrumb',
    // // 'primeng/button',
    // 'primeng/buttongroup',
    // 'primeng/card',
    // 'primeng/carousel',
    // 'primeng/cascadeselect',
    // 'primeng/chart',
    // 'primeng/checkbox',
    // 'primeng/chip',
    // 'primeng/colorpicker',
    // // 'primeng/config',
    // 'primeng/confirmdialog',
    // 'primeng/confirmpopup',
    // 'primeng/contextmenu',
    // 'primeng/dataview',
    // // 'primeng/datepicker',
    // 'primeng/dialog',
    // 'primeng/divider',
    // 'primeng/dock',
    // // 'primeng/dom',
    // 'primeng/dragdrop',
    // 'primeng/drawer',
    // 'primeng/dynamicdialog',
    // 'primeng/editor',
    // 'primeng/fieldset',
    // 'primeng/fileupload',
    // 'primeng/floatlabel',
    // // 'primeng/fluid',
    // 'primeng/focustrap',
    // 'primeng/galleria',
    // 'primeng/iconfield',
    // // 'primeng/icons',
    // // 'primeng/icons/angledoubledown',
    // // 'primeng/icons/angledoubleleft',
    // // 'primeng/icons/angledoubleright',
    // // 'primeng/icons/angledoubleup',
    // // 'primeng/icons/angledown',
    // // 'primeng/icons/angleleft',
    // // 'primeng/icons/angleright',
    // // 'primeng/icons/angleup',
    // // 'primeng/icons/arrowdown',
    // // 'primeng/icons/arrowdownleft',
    // // 'primeng/icons/arrowdownright',
    // // 'primeng/icons/arrowleft',
    // // 'primeng/icons/arrowright',
    // // 'primeng/icons/arrowup',
    // // 'primeng/icons/ban',
    // // 'primeng/icons/bars',
    // // 'primeng/icons/baseicon',
    // // 'primeng/icons/blank',
    // // 'primeng/icons/calendar',
    // // 'primeng/icons/caretleft',
    // // 'primeng/icons/caretright',
    // // 'primeng/icons/check',
    // // 'primeng/icons/chevrondown',
    // // 'primeng/icons/chevronleft',
    // // 'primeng/icons/chevronright',
    // // 'primeng/icons/chevronup',
    // // 'primeng/icons/exclamationtriangle',
    // // 'primeng/icons/eye',
    // // 'primeng/icons/eyeslash',
    // // 'primeng/icons/filter',
    // // 'primeng/icons/filterfill',
    // // 'primeng/icons/filterslash',
    // // 'primeng/icons/home',
    // // 'primeng/icons/infocircle',
    // // 'primeng/icons/minus',
    // // 'primeng/icons/pencil',
    // // 'primeng/icons/plus',
    // // 'primeng/icons/refresh',
    // // 'primeng/icons/search',
    // // 'primeng/icons/searchminus',
    // // 'primeng/icons/searchplus',
    // // 'primeng/icons/sortalt',
    // // 'primeng/icons/sortamountdown',
    // // 'primeng/icons/sortamountupalt',
    // // 'primeng/icons/spinner',
    // // 'primeng/icons/star',
    // // 'primeng/icons/starfill',
    // // 'primeng/icons/thlarge',
    // // 'primeng/icons/times',
    // // 'primeng/icons/timescircle',
    // // 'primeng/icons/trash',
    // // 'primeng/icons/undo',
    // // 'primeng/icons/upload',
    // // 'primeng/icons/windowmaximize',
    // // 'primeng/icons/windowminimize',
    // 'primeng/iftalabel',
    // 'primeng/image',
    // 'primeng/imagecompare',
    // 'primeng/inplace',
    // 'primeng/inputgroup',
    // 'primeng/inputgroupaddon',
    // 'primeng/inputicon',
    // 'primeng/inputmask',
    // 'primeng/inputnumber',
    // 'primeng/inputotp',
    // // 'primeng/inputtext',
    // 'primeng/keyfilter',
    // 'primeng/knob',
    // 'primeng/listbox',
    // 'primeng/megamenu',
    // 'primeng/menu',
    // 'primeng/menubar',
    // 'primeng/message',
    // 'primeng/metergroup',
    // 'primeng/multiselect',
    // 'primeng/orderlist',
    // 'primeng/organizationchart',
    // 'primeng/overlay',
    // 'primeng/overlaybadge',
    // 'primeng/paginator',
    // 'primeng/panel',
    // 'primeng/panelmenu',
    // 'primeng/password',
    // 'primeng/picklist',
    // 'primeng/popover',
    // 'primeng/progressbar',
    // 'primeng/progressspinner',
    // 'primeng/radiobutton',
    // 'primeng/rating',
    // // 'primeng/ripple',
    // 'primeng/scroller',
    // 'primeng/scrollpanel',
    // 'primeng/scrolltop',
    // 'primeng/select',
    // 'primeng/selectbutton',
    // 'primeng/skeleton',
    // 'primeng/slider',
    // 'primeng/speeddial',
    // 'primeng/splitbutton',
    // 'primeng/splitter',
    // 'primeng/stepper',
    // 'primeng/steps',
    // 'primeng/styleclass',
    // 'primeng/table',
    // 'primeng/tabs',
    // 'primeng/tag',
    // 'primeng/terminal',
    // 'primeng/textarea',
    // 'primeng/tieredmenu',
    // 'primeng/timeline',
    // 'primeng/toast',
    // 'primeng/togglebutton',
    // 'primeng/toggleswitch',
    // 'primeng/toolbar',
    // 'primeng/tooltip',
    // 'primeng/tree',
    // 'primeng/treeselect',
    // 'primeng/treetable',
    // 'primeng/ts-helpers',
    // // 'primeng/usestyle',
    // // 'primeng/utils',
    // // /^consola\//,
    // // // /^@primeuix\//,
    // // '@primeuix/themes/aura',
    // // '@primeuix/themes/lara',
    // // '@primeuix/themes/material',
    // // '@primeuix/themes/nora',
  ],

  // features: {
  //   ignoreUnusedDeps: true, // Avoid Tailwind errors.
  // },

  // Please read our FAQ about sharing libs:
  // https://shorturl.at/jmzH0
});
